<?php
namespace Netatmo\Common;

class NAThermZone {
const THERMOSTAT_SCHEDULE_SLOT_DAY      = 0x00;
const THERMOSTAT_SCHEDULE_SLOT_NIGHT    = 0x01;
const THERMOSTAT_SCHEDULE_SLOT_AWAY     = 0x02;
const THERMOSTAT_SCHEDULE_SLOT_HG       = 0x03;
const THERMOSTAT_SCHEDULE_SLOT_PERSO    = 0x04;
const THERMOSTAT_SCHEDULE_SLOT_ECO      = 0x05;
const THERMOSTAT_SCHEDULE_HOT_WATER_ON  = 0x06;
const THERMOSTAT_SCHEDULE_HOT_WATER_OFF = 0x07;
}

?>
